### ISSUE TITLE
best_practices > call_with_invitation: ios code is incomplete

### ISSUE THREAD

**Issue by commencementtech** [ZEGOCLOUD/zegocloud_sdk_demos#1]
call/best_practices/call_with_invitation/ios

When calling from Android not show any dialogue. Also when calling from iOS and another person received it in that case it showing continues call after accepting the call.

**Comment by Yerannnnnn** [comment]
@commencementtech  The issue has been fixed. Please check. Thank you for your feedback.

**Comment by Yerannnnnn** [comment]
The issue has been fixed. Please take a look. Thank you for your feedback.
